// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABHQtgYYwD2e2rtZHQTwfxMQYvBuZP2BY',
    appId: '1:904729481349:web:4b0f5d3f294362151a99ec',
    messagingSenderId: '904729481349',
    projectId: 'banvemaybay-f7cd3',
    authDomain: 'banvemaybay-f7cd3.firebaseapp.com',
    storageBucket: 'banvemaybay-f7cd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzXTR9Fm3SM8jBn10kZV4Siwx-NJSGSw',
    appId: '1:904729481349:android:fc0fbd68dbebbf181a99ec',
    messagingSenderId: '904729481349',
    projectId: 'banvemaybay-f7cd3',
    storageBucket: 'banvemaybay-f7cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4rhTWhsMwS0ysavHY3ggHpcXrmwA5EY0',
    appId: '1:904729481349:ios:7610227a406d1a351a99ec',
    messagingSenderId: '904729481349',
    projectId: 'banvemaybay-f7cd3',
    storageBucket: 'banvemaybay-f7cd3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4rhTWhsMwS0ysavHY3ggHpcXrmwA5EY0',
    appId: '1:904729481349:ios:7610227a406d1a351a99ec',
    messagingSenderId: '904729481349',
    projectId: 'banvemaybay-f7cd3',
    storageBucket: 'banvemaybay-f7cd3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABHQtgYYwD2e2rtZHQTwfxMQYvBuZP2BY',
    appId: '1:904729481349:web:8fddd612a84b2c511a99ec',
    messagingSenderId: '904729481349',
    projectId: 'banvemaybay-f7cd3',
    authDomain: 'banvemaybay-f7cd3.firebaseapp.com',
    storageBucket: 'banvemaybay-f7cd3.firebasestorage.app',
  );

}